### ISSUE TITLE
Local InfluxDB

### ISSUE THREAD

**Issue by nickvsnetworking** [omnt/OpenMobileNetworkToolkit#10]
G'day team,

Finally got some time to play with this, but I can't seem to get the local InfluxDB connection to come up on the Debug or Release builds.

IIRC in the talk at OSMNC you mentioned logging Influx data to a file and the importing it - Is this this functionality?

I did a bit of debugging and it looks like when you tap "Setup Local DB" it tries to connect to an InfluxDB server running on localhost, but I can't find much online about running an InfluxDB server on Android, are you able to give me a point in the right direction here?

My use case is logging data on the phone and then uploading to InfluxDB when we have connectivity again, so pushing directly in Influx Cloud isn't an option.

![333771772-295df05f-2bde-41d4-ad3e-efaa57a91a11](https://github.com/omnt/OpenMobileNetworkToolkit/assets/26107392/1c406997-96ff-4c4e-9937-3d66f22cfb69)

**Comment by hajoha** [comment]
Hi,

what we have done so far, was to download Influx from [here](https://www.influxdata.com/downloads/) for the right [ABI](https://developer.android.com/ndk/guides/abis) and then start the binary via adb shell. 
I tried to integrate an InfluxDB via JNI (like we did with iPerf3) into the App but that wasn't very successful so far.

But you don't need all this for your use case; just enable `Log file` this will generate a file under `/sdcard/documents/omnt/log`.
In this file each new line is a [point](https://docs.influxdata.com/influxdb/v2/reference/syntax/line-protocol/).
Either you upload the file via Influx GUI or write a short script that uploads those files.
It is on our roadmap to have a list of generated files and to upload at a later point via App.
![image](https://github.com/omnt/OpenMobileNetworkToolkit/assets/9853102/348de172-641d-448d-a3da-2b47d573c250)


PS: I advice to set a tag `device=DEVICENAME` and measurement name (the naming is quite confusing since InfluxDB uses __measurement_). 
![image](https://github.com/omnt/OpenMobileNetworkToolkit/assets/9853102/3deed153-78bd-4b4e-aba4-8a252a4b3c4e)

**Comment by hajoha** [comment]
With [Rel. 0.3](https://github.com/omnt/OpenMobileNetworkToolkit/releases/tag/0.3), we finally wrote some [doc](https://github.com/omnt/OpenMobileNetworkToolkit/blob/main/docs/quick-start.md)!
